// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUrlApi() {
  return window['go']['main']['App']['GetUrlApi']();
}

export function ListPlaybackDevice() {
  return window['go']['main']['App']['ListPlaybackDevice']();
}

export function StartPlaybackDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPlaybackDevice'](arg1, arg2, arg3);
}
