// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetUrlApi():Promise<string>;

export function ListPlaybackDevice():Promise<Array<main.DeviceInfo>>;

export function StartPlaybackDevice(arg1:number,arg2:string,arg3:string):Promise<void>;
